/**
 * Backfill: regenerate every existing "drop-*" blog post with the current
 * article template (>= 600 chars, sectioned, live badge data). The old posts
 * were generated by the pre-rebuild short template and stay short forever
 * otherwise — content is machine-owned (is_auto), so regenerating is safe.
 *
 * Usage: npx tsx scripts/backfill-drop-posts.ts [--dry]
 */
import { config } from "dotenv";
config({ path: ".env.local" });

async function main() {
  const dry = process.argv.includes("--dry");
  const admin = await import("../src/lib/supabase/admin");
  const { buildDropArticle } = await import("../src/lib/blog");
  const { logChange } = await import("../src/lib/changelog");
  const createAdminClient = admin.createAdminClient;

  const supabase = createAdminClient();

  const { data: posts, error } = await supabase
    .from("blog_posts")
    .select("id,slug,cover_url")
    .eq("status", "published")
    .like("slug", "drop-%");
  if (error) throw error;
  console.log(`drop posts found: ${posts?.length ?? 0}`);

  // Category context from the live catalog (single read).
  const { data: badges } = await supabase
    .from("badges")
    .select("category,status");
  const catTotals = new Map<string, number>();
  const catActive = new Map<string, number>();
  for (const row of (badges ?? []) as Array<{ category: string; status: string }>) {
    catTotals.set(row.category, (catTotals.get(row.category) ?? 0) + 1);
    if (row.status === "active") {
      catActive.set(row.category, (catActive.get(row.category) ?? 0) + 1);
    }
  }

  let updated = 0;
  let skipped = 0;
  let failed = 0;
  for (const post of posts ?? []) {
    const badgeSlug = post.slug.slice(5);
    const { data: badge, error: badgeError } = await supabase
      .from("badges")
      .select(
        "slug,title,set_id,image_url_2x,category,is_paid,how_to_earn,start_date,end_date,rarity_tier,rarity_score,description,created_at,source",
      )
      .eq("slug", badgeSlug)
      .maybeSingle();
    if (badgeError || !badge) {
      skipped += 1;
      continue;
    }
    const { content, excerpt } = buildDropArticle(
      {
        slug: badge.slug,
        title: badge.title,
        setId: badge.set_id,
        imageUrl2x: badge.image_url_2x,
        category: badge.category,
        isPaid: badge.is_paid,
        howToEarn: badge.how_to_earn,
        startDate: badge.start_date,
        endDate: badge.end_date,
        rarityTier: badge.rarity_tier,
        rarityScore: badge.rarity_score,
        description: badge.description,
      },
      {
        detectedAt: badge.created_at,
        source: badge.source,
        catalogTotal: badges?.length ?? 0,
        categoryCount: catTotals.get(badge.category),
        categoryActive: catActive.get(badge.category),
      },
    );
    if (dry) {
      console.log(`[dry] ${post.slug}: ${content.length} chars`);
      updated += 1;
      continue;
    }
    const { error: updateError } = await supabase
      .from("blog_posts")
      .update({ content, excerpt, cover_url: badge.image_url_2x ?? post.cover_url })
      .eq("id", post.id);
    if (updateError) {
      console.warn(`[backfill] failed ${post.slug}:`, updateError.message);
      failed += 1;
    } else {
      updated += 1;
    }
  }

  console.log(`updated: ${updated}, skipped (badge missing): ${skipped}, failed: ${failed}${dry ? " (DRY)" : ""}`);
  if (!dry && updated > 0) {
    await logChange({
      kind: "data_sync",
      title: `Drop-post backfill: ${updated} articles regenerated`,
      body: `All ${updated} machine-written drop articles were regenerated with the new >= 600-character template using live badge data (rarity, claim window, category context). ${skipped} posts had no matching badge and were left untouched.`,
      payload: { updated, skipped, failed },
    });
    console.log("changelog row written");
  }
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
