/**
 * Seeds the gamification blog series: one 300+ word post for the XP system,
 * BadgesCoins, wheel, achievements, stealing, profiles, visitors, the feed, the FAQ,
 * the arcade hub and each of the 13 games. Idempotent by slug.
 *
 * Run: npx tsx scripts/seed-gamification-blog.ts
 */
import { config } from "dotenv";

config({ path: ".env.local" });

function w(text: string): number {
  return text.trim().split(/\s+/).length;
}

interface Post {
  slug: string;
  title: string;
  excerpt: string;
  content: string;
  tags: string[];
}

const posts: Post[] = [];

posts.push({
  slug: "xp-level-system-explained",
  title: "The XP and Level System, Fully Explained",
  excerpt: "Levels 1 to 100, 100 unique sparkle badges, daily streaks and exactly how every XP point is earned.",
  tags: ["xp", "levels", "guide"],
  content:
    "Every collector on Twitch Badges Database now has a level, and that level is earned point by point through genuine badge-collecting activity. The system spans exactly one hundred levels. Level one begins at zero experience, and each subsequent level requires 100 XP plus an additional 50 XP per level above one — in other words, advancing from level 9 to 10 costs 500 XP while the final push from 99 to 100 costs a hefty 5,000 XP. Reaching the maximum therefore represents a total investment of 254,900 experience points, a mountain that rewards long-term dedication rather than a single lucky afternoon.\n\nXP flows from clearly defined sources. The daily login bonus grants 10 XP immediately and adds 5 more per consecutive streak day, up to a bonus of 50, which means a perfect month starts paying 60 XP before you have done anything else. Unlocking a Twitch badge is the crown jewel of the economy: every newly synced badge awards a massive 1,000 XP plus 500 BadgesCoins, so a collector who claims fifteen badges during a single event weekend instantly banks 15,000 XP. Achievements add between 50 and 5,000 XP depending on their rarity class. Arcade games contribute +2 XP per played round and +10 XP per victory, deliberately capped at 100 XP per day so that games remain a fun side dish rather than replacing actual collecting.\n\nEach of the hundred levels carries its own uniquely designed, sparkle-animated level badge rendered as a shield with the level number, themed in nine escalating brackets from stone gray at the low end through emerald, sapphire, amethyst, rose, amber and gold up to the inferno and finally the rainbow conic mythic crown at level 100. This badge is permanently displayed on your profile next to your name — it cannot be hidden, because your level is public information and part of the leaderboard identity. Level-ups are broadcast to the live activity feed, letting the whole community celebrate every milestone with you.",
});

posts.push({
  slug: "coin-economy-guide",
  title: "BadgesCoins: The Arcade Currency of Badge Collectors",
  excerpt: "How BadgesCoins are earned, spent, bet, stolen and rained — the complete economy guide.",
  tags: ["BadgesCoins", "economy", "guide"],
  content:
    "BadgesCoins are the playful hard currency of the arcade. Unlike XP, which only ever grows and determines your level, BadgesCoins circulate: they are won, bet, lost, stolen and gifted. Your balance is displayed on your profile and in the arcade header so you always know exactly what you can afford to risk.\n\nEarning BadgesCoins follows the same philosophy as XP. The daily login bonus pays 50 BadgesCoins plus 25 additional BadgesCoins per streak day, capped at a 250 bonus, so consistent visitors quickly double their baseline income. Each synced Twitch badge pays 500 BadgesCoins, achievements pay between 100 and an enormous 50,000 for the one-in-a-hundred-million Turbo jackpot achievement, game victories pay out according to each game's multiplier table, and wheel spins bundle BadgesCoins with their XP prizes. There is also the charming coin rain: any visitor to your profile can trigger one per day, dropping a single coin into your balance with a small animation — a tiny but heartwarming gesture between collectors.\n\nSpending happens in the arcade. Every one of the thirteen games takes a configurable bet between 10 and 5,000 BadgesCoins depending on the game's risk profile. Coin heists add a strategic layer: attempting to steal from another collector costs the attempt price that the victim configured, paid to the victim if your heist fails. This creates a fascinating mini-economy where high-profile collectors with fat wallets become targets and must decide whether to disable stealing, raise the attempt price to deter casual thieves, or treat successful defenses as income.\n\nThe economy is deliberately closed and worthless outside the site. BadgesCoins cannot be bought with money, there are no purchases anywhere in the system, and no pay-to-win shortcuts exist. Every coin in circulation was earned by logging in, collecting badges, winning games or robbing someone who did. That makes balances a pure trophy of activity, skill and nerve — and makes every 777-coin balance (a real achievement, by the way) worth bragging about.",
});

posts.push({
  slug: "wheel-of-fortune-and-turbo-jackpot",
  title: "The Wheel of Fortune and the 1:100,000,000 Turbo Jackpot",
  excerpt: "One free daily spin, 25 to 2,500 XP prizes, and the rarest winnable prize on the entire site.",
  tags: ["wheel", "turbo", "jackpot"],
  content:
    "Once per day, every logged-in collector gets a free spin of the Wheel of Fortune — and unlike everything else in the arcade, the wheel costs nothing at all. It is a pure gift, a daily ritual, and the only place on the site where you can win the single rarest prize we have ever offered.\n\nThe wheel carries seven regular segments plus one very special one. The most common outcome is +25 XP, which lands far more often than anything else, followed by +50, +100, +250, +500, +1,000 and the top prize of +2,500 XP, each progressively rarer following a carefully weighted distribution. Every prize also bundles bonus BadgesCoins so that even the smallest win feels tangible: 10 BadgesCoins at the bottom, 1,000 BadgesCoins at the very top. Spin results are announced in the live activity feed, which means the community collectively witnesses every big win — and there have been some genuinely dramatic 2,500 XP spins already.\n\nThen there is the golden segment. One slot on the wheel holds a complete Twitch Turbo subscription, awarded with a probability of exactly 0.00000001 — one in one hundred million. To put that number in perspective: if every visitor of the site spun once per day, the jackpot would statistically fire once every several hundred thousand years of combined activity. It is, by design, almost impossible. And yet it is real: the winner receives the Turbo subscription, 5,000 bonus XP, 50,000 BadgesCoins and the 'One in a Hundred Million' special achievement that no amount of grinding can ever replicate. The system also automatically publishes a celebratory blog post the moment it happens, because an event this rare deserves documentation. Check the wheel daily, keep your streak alive, and remember — the odds are astronomical, but they are not zero.",
});

posts.push({
  slug: "achievements-system-125-trophies",
  title: "123 Achievements: The Complete Trophy Wall",
  excerpt: "50 common milestones, 48 creative challenges and 25 truly unexpected specials — each with its own sparkle badge.",
  tags: ["achievements", "guide"],
  content:
    "Achievements are the long-term soul of the gamification system. There are exactly 123 of them, split into three classes with distinct personalities, and every single one awards XP, BadgesCoins and achievement points plus a dedicated sparkle-animated badge that appears in the hero showcase box on your profile for everyone to admire.\n\nThe fifty common achievements cover the classic milestones every progression system needs: first login, login streaks of 7, 30 and 100 days, owning 10, 50, 100 or 250 badges, reaching levels 5 through 100, holding 100 to 100,000 BadgesCoins, playing your first round and your five-hundredth, spinning the wheel ten and fifty times, unlocking your first achievement and your hundredth. They form the reliable backbone of progression — the trophies everyone can earn simply by being an active collector.\n\nThe forty-eight creative achievements are where the system develops a personality. Night Owl rewards claiming a daily bonus between midnight and five in the morning. Cursed Dice demands ten consecutive game losses. Phoenix asks you to lose 1,000 BadgesCoins and then rebuild your balance to 1,000 again. High Roller wants a single 1,000-coin bet while Cautious Gambler wants ten wins without ever betting more than ten BadgesCoins. Sharpshooter requires 90 percent accuracy in Shoot the Badges, Speedrunner demands a memory run under thirty seconds, and Time Traveler is only unlockable by owning a badge that first appeared in 2017 or earlier. Game-specific challenges like the seven-step coin flip ladder, green-zero roulette hits and ten-streak quiz runs round out a list designed to make you play differently.\n\nThe final twenty-five are the specials — genuinely unexpected trophies that reward bizarre coincidences and extremes. Level 42 ('Answer to Everything') and Level 69 ('Nice') exist purely because the numbers are funny. Lucky Sevens requires an exact 777-coin balance. The 3 AM Gambler needs a game won in a single specific night hour. Badge Birthday fires on the anniversary of your Twitch account's creation. And at the very top sits 'One in a Hundred Million', reserved exclusively for the Turbo jackpot winner. The evaluation engine runs automatically after every XP event, so you never claim anything manually — trophies simply find you.",
});

posts.push({
  slug: "steal-BadgesCoins-heists",
  title: "Coin Heists: How Stealing Works (and How to Defend)",
  excerpt: "Share-link targets, configurable attempt prices, level-based success chances and flood protection.",
  tags: ["steal", "BadgesCoins", "pvp"],
  content:
    "Not all income has to be earned honestly. The heist system lets any collector attempt to steal BadgesCoins from any other collector, turning every fat wallet on the leaderboard into a potential target and every profile visit into a moment of evaluation.\n\nHere is how an attempt works. You open another collector's profile and press the heist button. The attempt immediately costs the price that the victim has configured — anywhere from zero to 10,000 BadgesCoins. The system then calculates your success chance: a base of fifty percent, shifted by one percentage point for every level of difference between thief and victim, always clamped between twenty and eighty percent. Higher-level thieves have a genuine edge over newcomers, but nobody is ever safe and nobody is ever hopeless. If the heist succeeds you steal a random amount up to the victim's configured maximum haul, never more than ten percent of their current balance. If it fails, the attempt price you paid goes directly to the victim — meaning failed heists are literally a gift to your target.\n\nVictims hold meaningful defensive controls. In your settings you can disable stealing on your profile entirely, turning yourself into a bank vault that cannot be robbed but also never collects attempt-price income. You can raise the attempt price to a level that filters out casual opportunists. And you can cap the maximum haul so that even a successful heist hurts less than a bad night in the arcade. Defended heists count toward the Fortress achievement, while successful defenses pay — a pattern that rewards exactly the kind of high-balance, high-level collectors thieves love to target.\n\nAbuse is prevented by a strict flood check: one attempt per victim per five minutes, hard-capped at six attempts per thief per hour. Every heist, successful or defended, appears in the live activity feed, so the community watches the crime wave in real time. Robin Hood would feel at home here.",
});

posts.push({
  slug: "profile-customization-35-features",
  title: "35 Ways to Make Your Profile Yours",
  excerpt: "20 common customization settings and 15 creative extras — from aura glows to pixel avatars.",
  tags: ["profiles", "customization"],
  content:
    "Your profile is your museum, and museums deserve good interior design. The new customizer in your settings exposes thirty-five switches and dials, split into a practical common set and a genuinely playful creative set.\n\nThe twenty common settings cover the fundamentals of identity. Choose your display name and a title that appears next to it, write your bio, and set a banner image with an adjustable darkness overlay so text stays readable over busy artwork. Two accent colors drive your entire profile theme. Pick between four font families, three card styles (glass, solid or outline), three corner-radius personalities and two layout densities. Your avatar can wear one of five frames — plain, ring, double ring, glow or crown. The badge showcase supports grid, row or carousel layouts, and you decide individually whether stats, inventory, the level bar, the coin balance and the visitor widget are public. Social links for Twitter and Discord round out the classics.\n\nThe fifteen creative settings are where profiles stop being documents and start being experiences. Enable the aura and a soft glow in your accent color breathes around your header. Falling badge particles drift gently down the page. Your name can cycle through a rainbow gradient animation; the banner gets a periodic shine sweep; showcase badges tilt in 3D under the cursor. The pixel avatar option retro-fies your Twitch picture. A scrolling ticker narrates your latest achievements, a time-of-day greeting banner welcomes visitors differently at dawn, noon and midnight, and your level badge's halo color is separately configurable so it can match — or deliberately clash with — your theme. The visitors widget becomes an avatar marquee, the coin-rain button pulses invitingly, a badge cursor replaces the pointer, effects have three intensity levels for accessibility, and a status bubble carries a custom mood line. Twenty themes, five profile palettes, one identity: yours.",
});

posts.push({
  slug: "live-activity-feed",
  title: "The Live Feed: Watch the Whole Community Play",
  excerpt: "Every XP gain, every game round, every achievement and every heist — streaming in near real time.",
  tags: ["feed", "community"],
  content:
    "The live activity feed is the heartbeat of the gamification system. Every single event that moves a number anywhere on the site flows into one public, continuously updating stream: daily bonus claims, badge unlocks with their thousand-point swings, wheel spins, all thirteen arcade games with their wins and losses, every achievement the moment it fires, every level-up, every coin heist whether successful or defended, every coin rain, and — should the impossible ever happen — the Turbo jackpot with full fanfare.\n\nThe feed page polls every five seconds and prepends fresh events with a subtle animation, so watching it feels like standing in a busy arcade. Each entry shows the actor's avatar and a link to their profile, a human-readable sentence describing what happened, the event category as a color-coded dot, a relative timestamp, and the exact XP and coin deltas involved. The transparency is deliberate: because every point is public, the economy stays trustworthy. You can literally watch someone win the 2,500 XP wheel prize, then watch them lose it all in the slots three minutes later, then watch someone rob them and get defended.\n\nBeyond entertainment, the feed serves a social function. It turns a database website into a place where things happen — where you recognize recurring names, follow rivalries, and feel the presence of other collectors working the same drops you are. The homepage shows a compact version of the latest events, and every profile links into the feed context around a player. Pause and resume controls keep it polite when you want to read without movement. If the arcade is the playground, the feed is the crowd around it.",
});

posts.push({
  slug: "profile-visitors-view-counts",
  title: "Who Visited Your Profile? Now You Know",
  excerpt: "Latest-visitor widgets, view counts, and the five-minute reload block that keeps numbers honest.",
  tags: ["profiles", "visitors"],
  content:
    "Every public profile now tracks its audience. The total view count is displayed prominently, and below it runs a row of the latest visitors — actual avatars of real collectors who stopped by, each linking to their own profile so you can return the visit. It is a small feature that changes the texture of the site: profiles stop being static exhibits and become social spaces with foot traffic you can see.\n\nThe engineering challenge with view counters is always honesty. Naive counters reward refreshing your own page fifty times; nobody wants that. Every view counter on this site — profile views and blog post views alike — therefore uses a five-minute per-IP deduplication window. A visitor's IP is hashed with a server-side salt into a pseudonymous token that cannot be reversed into an address, and within any five-minute window that token counts at most once per target. Genuine traffic across time accumulates normally; rapid reloads simply merge into a single count. The same hash powers the visitor log without ever storing usable personal data.\n\nThe visitor row deliberately shows only named, logged-in visitors with public profiles — anonymous traffic increments the count but leaves no faces. Visiting other profiles is itself gamified: fifty profile visits earn the Window Shopper creative achievement, being visited by twenty-five different people earns Local Celebrity, and a thousand views earns Certified Celebrity. Meanwhile the Ghost Town special achievement exists for the exact opposite: a week-old profile that somehow still has zero visitors. Whether you are popular, curious, or gloriously ignored, the system noticed.",
});

for (const [slug, title, tags, body] of [
  ["rps-rock-paper-scissors", "Rock-Paper-Scissors: The Honest Duel", ["games", "rps"],
   "Rock-Paper-Scissors is the oldest wager in human history, and our version strips it down to its purest form: you, the bot, and a bet. Choose rock, paper or scissors after setting your stake between 10 and 5,000 BadgesCoins. The bot picks uniformly at random — genuinely, from a server-side cryptographic RNG — so there is no pattern to exploit and no psychology to leverage. What remains is pure probability management: a one-in-three chance to double your bet, a one-in-three chance to lose it, and a one-in-three tie that refunds your stake entirely and lets you replay without cost.\n\nThe elegance is in the tie rule. Because pushes return your bet, the effective house edge is zero: the game is mathematically fair over time, which makes it the lowest-variance warm-up in the arcade. Players grinding the RPS Perfectionist special achievement — a seventy percent win rate over twenty-plus duels — will feel the variance tighten with sample size, while those chasing the Mind Reader creative achievement need five consecutive wins, a run the bot will stubbornly resist about two hundred forty-two times out of two hundred forty-three.\n\nEvery duel feeds the live activity feed, increments your games-played statistics, contributes +2 XP (+10 on a win) toward the daily hundred-XP game cap, and updates streak flags that the achievement engine evaluates automatically. The interface renders the three options as clean stroke icons with instant result feedback showing both picks side by side. It is the game you play between badge syncs — quick, honest, and always one more round."],
  ["badges-of-ra-6-deluxe-slots", "Badges of Ra 6 Deluxe: The Slot Machine", ["games", "slots"],
   "Badges of Ra 6 Deluxe is the arcade's flagship slot machine, lovingly modeled after the classic Book-of-Ra formula but with every symbol replaced by genuine Twitch badges pulled live from the catalog. Five reels spin three visible rows each, and the paytable uses real badge artwork: Prime Gaming, Turbo, Bits, Founder, SUBtember and WSCI symbols in ascending value, plus the Book of Badges scatter that unlocks the big wins.\n\nFive fixed paylines cross the grid — three horizontals and both diagonals — and wins pay left-to-right for three, four or five matching symbols at multipliers of 1.5×, 4× and 15× the per-line stake respectively, scaled further by each symbol's individual value rating. The scatter is where fortunes shift: three Books anywhere on the grid pay 2× your total bet, four pay 5×, and five scattered Books detonate into a 20× celebration. The theoretical maximum win per spin is capped at twenty-five times the stake, keeping the economy sane while preserving genuine jackpot moments.\n\nBets run from 10 to 2,000 BadgesCoins, and every spin is resolved entirely server-side: the reel grid is generated on the server, the client merely animates the reveal, so outcomes are tamper-proof. Wins, losses and scatter counts feed the live feed and statistics, three-plus-scatter spins flag toward the Scatter! creative achievement, and a single 5,000-coin payout triggers Ra's Jackpot in the specials. The reels animate with a pulsing spin state before snapping to the result — close your eyes and you can almost hear the casino."],
  ["shoot-the-badges", "Shoot the Badges: A Moorhuhn Revival", ["games", "shoot"],
   "Shoot the Badges is our love letter to Moorhuhn, the legendary German shooting gallery that ate more office hours than any spreadsheet. The formula translates perfectly to badge collecting: for thirty seconds, Twitch badges fly across a twilight range, and every click that connects scores a hit. There are no ammo limits and no reloads — only your reflexes, your mouse precision, and a ticking clock that turns composure into panic around the twenty-second mark.\n\nScoring is accuracy-based rather than volume-based, which is the crucial design decision. Your payout multiplier equals 2.2 times your accuracy minus 0.8, clamped between a total loss and a 1.2× profit on top of the returned stake. Spraying wildly at everything yields maybe forty percent accuracy and steadily drains your bet; deliberately picking off the clean shots while letting crowded clusters pass can push past eighty percent and turn a tidy profit. The server validates and clamps all reported scores, so the leaderboard stays honest.\n\nThe skill ceiling rewards real technique: leading targets, prioritizing slower inbound badges, resisting the temptation to double-click near-misses. Accuracy of ninety percent or better flags the Sharpshooter creative achievement, and fifty lifetime rounds unlock Badge Hunter. Every round pays +2 XP (+10 on profit) toward the daily game cap and echoes into the live feed. Set your bet between 10 and 2,000 BadgesCoins, take a breath, and remember the oldest Moorhuhn wisdom: the fast ones are worth the same as the slow ones — but only if you actually hit them."],
  ["badge-memory", "Badge Memory: Speedrun the Pairs", ["games", "memory"],
   "Badge Memory takes the classic concentration game and gives it a collector's soul. Twelve face-down cards hide six pairs of genuine Twitch badge artwork, shuffled fresh every round. Flip two at a time; matches stay revealed, mismatches flip back after a beat. Clear the board and your performance converts directly into BadgesCoins.\n\nThe payout formula rewards the two skills memory games actually test: speed and cleanliness. Your multiplier starts at 1.6 and loses ground to the clock at one point per ninety seconds elapsed, plus a heavier six-point penalty per mismatch. Finish a board in twenty seconds without a single wrong flip and you approach the maximum 1.2× profit; stumble through in two minutes with eight misses and you will wish you had just spun the wheel instead. The tension between flipping fast (to beat the timer) and flipping carefully (to avoid miss penalties) is where every round lives or dies.\n\nTwo creative achievements attach to the extremes of that tension. Photographic demands a perfect board — zero mismatches, an exercise in spatial memory that sounds easy until the sixth pair. Speedrunner demands the whole board inside thirty seconds, which effectively forces confident first-guess flipping and forgives a couple of misses. Mastering both on the same run is the memory grandmaster challenge nobody has formally named yet. Bets run 10 to 2,000 BadgesCoins, results post instantly, and every round feeds the live activity stream. It is the arcade's purest brain game — no luck, no house edge, only you versus your own recall."],
  ["badge-quiz", "Badge Quiz: Prove You Know Every Pixel", ["games", "quiz"],
   "Badge Quiz is the trivia arena where badge knowledge becomes coin. Each round presents ten questions in a simple, brutal format: one genuine Twitch badge image against four title options pulled from the live catalog. Identify all ten and you approach the maximum multiplier; misidentify a few and the payout decays with your credibility. Questions are generated server-side from current catalog data, so the pool refreshes as badges rotate in and out — there is no static answer sheet to memorize, only actual familiarity with hundreds of badge artworks.\n\nThe multiplier scales at 2.1 times your correct ratio minus 0.8, clamped between total loss and a 1.2× profit. Perfect rounds are the holy grail: ten out of ten not only pays best but flags the Badge Professor creative achievement, demanding the sustained recognition that separates casual collectors from the genuinely obsessed. The distractor options are chosen from visually plausible candidates, which means the quiz quietly teaches visual discrimination — the difference between similar event badges from consecutive years, between subtly different bits milestones, between a 2025 and 2026 world-championship design.\n\nRounds cost between 10 and 2,000 BadgesCoins, resolve instantly, and feed both the live activity stream and your game statistics. Because the badge pool draws from the real catalog including newly seeded drops, dedicated players who follow the /active page and read badge detail pages genuinely perform better — making Badge Quiz the only arcade game where studying the rest of the website is the winning strategy. Consider that formal permission to browse badges all day."],
  ["coin-flip-ladder", "Coin Flip Ladder: Seven Steps to Glory", ["games", "coinflip"],
   "The Coin Flip Ladder compresses the entire psychology of gambling into one decision: how high do you dare climb? Pick heads or tails, then choose a target rung on a seven-step ladder before flipping. Every rung doubles your potential payout — but one wrong flip at any point and the whole stake vanishes. It is the purest expression of risk multiplication in the arcade.\n\nThe mathematics are deliberately transparent. Each individual flip is a fair fifty-fifty, but the ladder multiplies risk: reaching step seven requires seven consecutive correct calls, a 0.78 percent proposition paying roughly 97 percent of the true 128× fair value (a modest house edge that keeps the lights on). The expected-value-maximizing play is boring — one or two steps — while the heart wants the full seven and the Lucky Streak creative achievement that waits there. The interface makes the temptation physical: your chosen side glows, each surviving flip adds a coin token to the row, and one red token ends everything.\n\nBets span 10 to 5,000 BadgesCoins, which means the top ladder rung can pay out over 600,000 BadgesCoins on a max bet — the largest structured payout in the arcade outside the Turbo jackpot itself. Every ladder attempt, glorious or devastating, hits the live feed where spectators can watch someone flame out on step six for the fourth time today. The +2/+10 XP flows as usual. Choose your side, choose your greed level, and remember the ladder's oldest lesson: the BadgesCoins you did not cash out were never really yours."],
  ["higher-or-lower", "Higher or Lower: Trade on Rarity", ["games", "hilo"],
   "Higher or Lower turns the site's own rarity index into a trading floor. Each round shows you the TBRI rarity score of a badge — a number from zero to one hundred computed from owner scarcity, wear rates, obtainability, momentum and window brevity. Your job is simply to call whether the next randomly drawn badge will score higher or lower. Correct calls pay 1.95× the stake; wrong calls lose it. That's the whole game, and it is endlessly playable precisely because it is that simple.\n\nThe fascinating part is that skill genuinely exists here. The distribution of rarity scores is not uniform — most badges cluster between twenty and seventy, so a displayed score of fifteen is almost certainly going higher and a displayed ninety-five is almost a guaranteed 'lower'. The edges of the distribution are free money; the dangerous middle forties are a coin flip. Players who internalize the score distribution develop an intuitive edge, and the game quietly teaches the underlying rarity model better than any documentation page could. State persists between rounds: the revealed card becomes the new baseline, so streaks form naturally around whatever scores the deck deals.\n\nTen consecutive correct calls unlock the Rarity Sense creative achievement, a run that punishes greed in the middle range and rewards patience at the extremes. Bets run 10 to 5,000 BadgesCoins, each round feeds the live activity stream, and the XP trickle adds up behind the daily cap. It is the arcade game most directly wired into the database itself — you are, quite literally, trading on the catalog."],
  ["badge-roulette", "Badge Roulette: Red, Black and the Cruel Green", ["games", "roulette"],
   "Badge Roulette is classic European roulette distilled to its essential bet: pick a color, watch the wheel, feel everything. Thirty-seven pockets numbered zero to thirty-six — eighteen red, eighteen black, and one green zero that belongs to the house and to nobody's plans. Red and black pay a clean 2× on hits; the green zero pays a mouthwatering 14×. The number history strip below the wheel shows the last twelve results as colored chips, which is scientifically meaningless and emotionally indispensable.\n\nThe green bet is the game's soul. At one in thirty-seven, a 2.7 percent hit rate against a fourteen-times payout, it is a terrible value bet in pure expected-value terms — and yet when it lands, the celebration is disproportionate: an instant 14× multiplication of your stake, a highlighted ring on the history chip, and the Green Zero creative achievement flag firing for the six-hundredth player to experience it. Chasing green is how bankrolls die; hitting it accidentally on a hunch is how legends are made in the activity feed.\n\nBets span 10 to 5,000 BadgesCoins, resolution is fully server-side, and every spin lands in the live feed with its number and color. There is no strategy — that is the point. Roulette is where the arcade's luck purists go to feel something, where streak-logic and gambler's fallacy bloom eternally, and where the green zero waits, patient as ever, for the next believer."],
  ["badge-blackjack", "Badge Blackjack: Pick Your Line", ["games", "blackjack"],
   "Badge Blackjack takes the world's most famous card game and reshapes it around a single elegant decision: before the deal, you set your draw threshold between twelve and twenty. The dealer then plays fixed casino rules — drawing to seventeen — while your hand auto-draws until it reaches your chosen line. It is blackjack as strategy selection rather than card-by-card drama, and it captures ninety percent of the game's real decision space in one slider.\n\nThe strategy landscape is genuinely interesting. Drawing to twelve risks busting constantly but beats the dealer's seventeen whenever the dealer would have stood on a mediocre hand. Drawing to nineteen or twenty rarely busts but ties and loses to dealer twenties. The classic sixteen/seventeen boundary is where the real edge lives, exactly as in the physical game. A two-card twenty-one pays 2.5× instead of the standard 2×, ordinary wins double your stake, and exact ties push your bet back — making blackjack the arcade's most forgiving loss structure since bad rounds frequently just refund.\n\nFive consecutive winning hands flag the Card Shark creative achievement, and sustained excellence over twenty-plus hands feeds the streak counters the achievement engine watches. Bets run 10 to 5,000 BadgesCoins, every hand's cards and totals render clearly with the dealer's reveal, and results stream to the live feed. It is the thinking player's tables game — no instincts required mid-hand, just one honest decision about who you are: the twelve-daredevil, the seventeen-citizen, or the twenty-ascetic."],
  ["crack-the-vault", "Crack the Vault: Three Needles, One Nerve", ["games", "vault"],
   "Crack the Vault is the arcade's timing game — a pure test of nerve rendered as three rotating dials and a green target zone. Dial one spins at a moderate pace; dial two spins faster; dial three spins fast enough to make your pupils vibrate. Stop each needle inside its green window and the multiplier climbs: one match pays 1.5×, two pay 3×, and three perfect stops pay the full 3× top prize. Miss everything and the vault stays shut, keeping your stake.\n\nThe escalating speed is the entire difficulty curve. The first dial is nearly a formality — most players hit it while still feeling confident. The second dial introduces real doubt; the needle crosses the zone in a fraction of a second and the temptation to stop early, slightly before the green, ruins more runs than the speed itself. The third dial is where hands sweat: a blur of rotation where you must commit to a predicted stop rather than a reaction. Players describe entering a flow state on good runs and a fugue state on bad ones, which we consider a design success.\n\nThe Vault Cracker creative achievement demands three perfect stops, and the dedicated players who chase it develop personal rituals — counting rotations, breathing patterns, specific stop points. Because matches are validated server-side against clamped inputs, the leaderboard reflects actual timing skill rather than scripted perfection. Bets run 10 to 2,000 BadgesCoins, every attempt tells the feed whether the vault opened, and the top prize means one flawless run pays triple. One needle, one nerve, one shot."],
  ["scratch-the-badge", "Scratch the Badge: Nine Fields of Hope", ["games", "scratch"],
   "Scratch the Badge is the arcade's most tactile pleasure — a virtual scratch card with nine covered fields and the exact dopamine architecture of the physical thing. Buy a card, then reveal fields one at a time with satisfying click-by-click reveals. Underneath lurk seven symbol types; find any symbol three or more times and the card pays. Three of a kind doubles your money, four pays 6×, and discovering the elusive jackpot symbol under three fields simultaneously triggers a 20× celebration that briefly makes you the most interesting person in the live feed.\n\nThe psychological design is faithful to the genre's manipulative genius. Early reveals that match create hope; a mid-card mismatch manufactures the classic 'so close' feeling that has fueled scratch card purchases since the seventies. Because the symbol layout is generated and resolved entirely server-side before you reveal anything, the outcome is fixed at purchase — the reveals are pure theater, exactly like real scratch cards where the silver coating hides a destiny already printed. Somehow this does not diminish the pleasure at all; if anything, the knowledge that hope is technically meaningless makes each reveal funnier.\n\nCards cost 10 to 1,000 BadgesCoins, making this the arcade's lowest-stakes game and a pleasant palate cleanser between bigger gambles. The Golden Scratch creative achievement waits for a 20× jackpot card, and every result posts to the activity feed. Reveal corners first, centers first, or in a spiral — the ritual is yours, and the odds do not care, which is rather the point."],
  ["tower-of-badges", "Tower of Badges: The Cash-Out Climb", ["games", "tower"],
   "Tower of Badges is the arcade's purest pressure cooker: ten floors of rising risk, one cash-out decision, and absolutely no partial credit. Set your target floor before climbing, then watch the ascent resolve floor by floor. Each floor survived multiplies your payout — from 1.22× on floor one to 3.2× on the summit — but each floor also carries a failure chance that grows from eight percent at the base to over sixty percent near the top. One failure anywhere and the entire stake is gone. You cannot cash out mid-climb; the decision must be made before the first step, which transforms greed from an emotion into a number.\n\nThe probability structure creates genuinely agonizing choices. Floor five — the default target — survives about two-thirds of the time and pays 2.1×, a reasonable risk-reward balance. Floor ten survives roughly one climb in eight but pays 3.2×, and reaching the summit flags the Tower Climber creative achievement. The devious part is that mid floors like seven often tempt players with a survival rate around half and a 2.54× payout that feels safer than it is. Everyone develops a personal floor philosophy, and everyone eventually betrays it once.\n\nBets run 10 to 2,000 BadgesCoins, climbs resolve server-side with the animated tower filling floor by floor in green success or red ruin, and every attempt broadcasts to the live feed where spectators silently judge your floor choice. The crashed message — 'the tower guards caught you' — is designed to sting gently. Climb bravely, cash wisely, and remember the tower's truth: the view from floor ten is beautiful because almost nobody sees it."],
  ["drops-catcher", "Drops Catcher: Basket Case Championship", ["games", "catcher"],
   "Drops Catcher is the arcade's action game — thirty seconds of falling badges, one basket, and your mouse as the reflex engine. Badge icons rain from the top of the play field while bombs scatter among them; move the basket to catch badges and dodge explosions. Every caught badge is a point; every bomb caught costs three; every badge that hits the floor counts as a miss against your accuracy. When the timer dies, the performance converts to BadgesCoins through a formula that rewards volume and cleanliness in equal measure.\n\nThe payout multiplier computes 0.012 per catch minus 0.02 per miss, clamped between total loss and a 1.5× profit — meaning a hundred-badge run with modest misses pays the maximum, while sloppy rounds bleed value with every dropped badge. The bomb mechanic adds genuine tactical texture: sometimes it is correct to let a badge fall rather than dive through a bomb cluster, a split-second triage calculation that separates the coordinated from the frantic. One hundred catches in a single run flags the Golden Gloves creative achievement, the game's mastery trophy.\n\nBets run 10 to 2,000 BadgesCoins, the server clamps all reported scores against physically plausible bounds, and every round feeds the live activity stream — where a great catcher run is instantly recognizable by its suspiciously serene profit line. The basket follows your cursor with responsive immediacy, the thirty-second format fits perfectly between other games, and the skill progression from flailing to flow-state is steep and satisfying. Catch the drop; become the drop."],
] as Array<[string, string, string[], string]>) {
  posts.push({ slug, title, tags, excerpt: body.split(". ")[0] + ".", content: body });
}

posts.push({
  slug: "badge-arcade-grand-opening",
  title: "The Badge Arcade Is Open: 13 Games, One Economy",
  excerpt: "Everything launches today — XP, BadgesCoins, the wheel, 123 achievements, heists and the full arcade.",
  tags: ["arcade", "announcement"],
  content:
    "Today the Twitch Badges Database grows an entire arcade. Thirteen games go live, each themed entirely around Twitch badges and all running on one shared economy of BadgesCoins you earn by actually collecting. Alongside them: a hundred-level XP system with unique sparkle badges per level, a daily Wheel of Fortune whose top prize reaches 2,500 XP, a one-in-a-hundred-million Twitch Turbo jackpot, 123 achievements across three rarity classes, a coin-heist system with configurable defenses, thirty-five profile customization settings, visitor tracking with honest five-minute-deduped counters, and a public live feed where every point earned anywhere on the site streams past in real time.\n\nThe design philosophy stayed consistent throughout: gamify collecting, not spending. There are no purchases anywhere in the system. Every coin in circulation was earned through daily activity, badge unlocks, game wins or successful heists; every XP point traces back to genuine engagement with the badge catalog. Games deliberately cap their XP contribution at one hundred points per day so they remain dessert rather than replacing the main course of actual collecting. The wheel is free once per day precisely because the daily-visit ritual matters more than the bet size.\n\nFairness received particular care. All luck outcomes — slots, roulette, wheel segments, coin flips, blackjack draws, scratch layouts, tower failures — resolve on the server from outcomes the client never influences. Skill games validate and clamp reported scores against plausible bounds. Flood checks rate-limit game rounds and heists. View counters deduplicate per hashed IP. The result is an economy you can trust because you can watch every transaction in the public feed.\n\nEach game and system has its own detailed post in this blog series — browse the arcade tag for the full tour. Log in with Twitch, sync your badges for your first thousand-point bonuses, claim your daily wheel spin, and check the feed to watch the community's first chaotic evening unfold. The arcade never closes.",
});

posts.push({
  slug: "faq-and-blog-upgrade",
  title: "New: Comprehensive FAQ and Blog Upgrades",
  excerpt: "Twenty answers about the gamification system, plus view counters and emoji reactions on every post.",
  tags: ["faq", "blog", "announcement"],
  content:
    "Two supporting features ship alongside the arcade to keep the whole system understandable. First, a complete FAQ page answering the twenty questions every player eventually asks: what XP is worth, how the level curve bends, where BadgesCoins come from, how the daily streak bonus compounds, what the wheel pays, whether the Turbo jackpot is real (it is, at exactly one in a hundred million), how heist chances calculate, how to defend against thieves, what appears in the live feed, all thirty-five profile settings, how visitor counting stays honest, and where all the data comes from. The FAQ ships in every one of the site's eleven languages and carries FAQPage structured data so search engines can surface the answers directly.\n\nSecond, the blog itself grew social features. Every post now displays a view counter using the same five-minute per-IP deduplication as profile views, so the numbers reflect actual readers rather than refresh spasms. Below each post sit five emoji reactions — like, love, laugh, fire and wow — toggleable per visitor, with live counts that persist. The reaction set is deliberately small and universally readable across cultures, and each reaction is keyed to a hashed visitor token so counts stay honest without accounts.\n\nGoing forward, the auto-blog system documents itself: every new feature and every new game publishes its own minimum-three-hundred-word announcement post automatically, and special events — most dramatically a Turbo jackpot win — generate celebratory posts the moment they happen. This very series, thirteen game deep-dives plus system guides, is the format's debut. Knowledge is a feature; now it is a documented one.",
});

const EXTENSIONS: Record<string, string> = {
  "rps-rock-paper-scissors": " The betting interface keeps friction near zero: a bet bar with quick-select chips at 10, 50, 100 and 500 BadgesCoins, a numeric field up to the 5,000-coin ceiling, and three large hand buttons that respond the instant the round resolves. Result panels show both picks side by side with color-coded verdicts, so the outcome reads instantly even mid-session. Because ties refund completely, aggressive bettors can hold maximum stakes indefinitely without bleeding; the only way RPS costs money is losing outright, which happens exactly one round in three. That structure makes it the mathematically safest place in the arcade to park large bets while waiting for wheel resets or badge syncs, and the live feed's steady stream of RPS rounds confirms that plenty of collectors treat it exactly that way.",
  "shoot-the-badges": " The range is a twilight-gradient field where badges spawn from the edges and drift on individual trajectories, with up to six targets on screen at once and new spawns entering continuously. The crosshair cursor replaces the pointer the moment the round starts, the hit detection radius is forgiving, and the HUD shows a countdown and your running hit counter in the top corners. After the buzzer, a summary line reports your raw numbers and accuracy percentage before the server converts them into the payout. The skill curve is real: first sessions end in the red while your wrist calibrates to target speeds, but dedicated players report steady progression past seventy percent accuracy within a dozen rounds, at which point the game becomes reliably profitable at any bet level.",
  "badge-memory": " The deck draws six pairs from the live badge catalog each round, so the game doubles as passive catalog familiarization: play enough memory and you will start recognizing badge sets on sight, which quietly improves your Badge Quiz performance too. Cards flip with a soft transition, matched pairs settle into emerald frames, and the mismatch bounce-back delay is tuned to exactly the duration where a wrong guess feels informative rather than punishing. Because there is no house edge and no random element beyond the shuffle, Badge Memory is the arcade's purest skill game, and the dual achievements for perfection and speed ensure that both careful players and frantic ones have something to chase.",
  "badge-quiz": " The quiz's question generation deserves a closer look because it is the arcade's most technically interesting game loop. Each round, the server samples ten badges from the current catalog and selects three distractor titles chosen to be genuinely confusing, often badges from the same set family or consecutive event years. That means the quiz difficulty scales automatically with your knowledge: casual players get obviously-wrong options to eliminate, while veterans face the true test of distinguishing one year's championship design from the next by a single accent color. The real payout is quieter than the BadgesCoins: players consistently report that a week of quiz rounds makes the entire badge catalog feel familiar in a way passive browsing never achieved. It is the only arcade game with a documented study strategy, and the study material is the website itself.",
  "coin-flip-ladder": " The interface renders each ladder rung as a live coin row that fills green as you survive and detonates red the instant a flip betrays you, with the potential payout recalculating in real time as you drag the target slider from one to seven. The slider label always shows the exact coin amount waiting at your chosen rung, so greed becomes a precise number rather than a vague feeling. Server-side resolution means the flip sequence is fixed before your first coin leaves your balance: no rerolling, no lucky-refresh tricks, just seven honest coin tosses standing between you and the largest structured payout in the arcade. Veterans develop unmistakable rhythms, and the seven-step dreamers' catastrophic fourth-step exits punctuate the activity feed like small fireworks.",
  "higher-or-lower": " The interface presents the current rarity score as an enormous tabular number flanked by two large call buttons, with the resolved comparison appearing beneath in color-coded verdict text so every round teaches something about the distribution. Because the revealed card becomes the next baseline, runs develop momentum, and watching that climb in the activity feed is half the spectator sport. New players should internalize one rule above all: the extreme scores at either end of the distribution are approximately free money, and the honest coin flips live only in the crowded middle. Once that intuition clicks, HiLo stops being a gamble and becomes a slow, deliberate harvest with occasional volatility, which is precisely what a game built on a transparent rarity formula should feel like.",
  "badge-roulette": " Betting UX stays deliberately minimal: three wide color buttons with their multipliers printed directly on them, no number grid, no split bets, no complexity beyond the one decision that matters. The history strip functions as the game's memory, twelve chips showing exactly where the wheel has been, with winning entries ringed so your personal hits glow in the sequence. Roulette's role in the arcade is the honest coin flip with better lighting: identical expected value to the fair games but wrapped in ceremony, streaks, and the perpetual seduction of green. Every spin posts to the live feed, so the community's collective red-black balance is public knowledge, and runs of five blacks in a row reliably summon a fresh wave of believers to the green button.",
  "badge-blackjack": " The card rendering keeps the classic feel: individual cards as bordered tiles with tabular totals beside each hand, the dealer's draw sequence revealing card by card, and outcome text in verdict colors. The 2.5x blackjack bonus for natural two-card twenty-ones adds a lottery shimmer to every initial deal, and the push-on-tie structure means a healthy share of hands simply evaporate without consequence, making blackjack the arcade's most forgiving loss structure. Strategy-minded players should experiment with the full threshold range at minimum stakes before committing, because the difference between drawing to fifteen and drawing to eighteen is worth real expected value against the dealer's fixed seventeen rule. Every hand posts to the live feed, and the stop-at slider means your entire blackjack philosophy is expressed in a single number you chose before the first card moved.",
  "crack-the-vault": " Visual feedback drives the entire experience: each dial is a thick-ringed circle with a glowing accent needle, the active dial highlights while the others idle, and a green tick marks the target zone. The geometry of every near-miss is visible for a full second after stopping, which is either instructive or painful depending on the outcome. The multiplier table is printed directly beneath the dials so the stakes of each stop are never in doubt. Because all three needles must be stopped deliberately, a round takes about ten seconds of genuine attention: no auto-play, no background spinning, just three decisions made under increasing time pressure. A run of successful cracks is one of the most recognizable patterns in the live feed.",
  "scratch-the-badge": " The card renders as a three-by-three grid of chunky tiles with the jackpot symbol rendered in warning gold so a triple cannot be mistaken for anything else. Reveal order is entirely yours, and the game logs nothing about your pattern, which somehow makes the ritual feel more personal. Because the entire symbol layout is decided at purchase time on the server, there is no skill component to argue with: Scratch the Badge is the arcade's purest concession to chance, and its low bet ceiling reflects that honestly. It slots perfectly into the gaps between higher-stakes games, and the live feed records every card's fate, with a jackpot landing in the stream like a small fireworks display.",
  "tower-of-badges": " The tower renders as a vertical stack of ten floor rows, each labeled with its multiplier, and your chosen cash-out floor glows while floors above sit dim and aspirational. During the climb each floor lights green as it is survived or red the instant the guards intervene. Probability intuition is the whole game: low floors fail rarely and pay little, high floors fail often and pay gloriously, and the interface recomputes nothing mid-climb because your decision was made at the bottom. That rigidity is the design: Tower of Badges is a game about who you are before the pressure starts, and the live feed keeps a public record of every answer.",
  "drops-catcher": " The play field is a twilight-gradient rectangle where badges spawn at randomized positions and fall at speeds ranging from gentle drift to genuine dive, while bombs rain down among them. Your basket tracks the mouse with immediate response, and the catch detection is forgiving at the edges: badges within roughly a basket-width count, so gliding across a cluster sweeps all of it. The thirty-second format creates three distinct phases: a calm opening, a frantic middle, and a desperate final five seconds where every player discovers they should have been positioning differently for the last ten. The server clamps all reported counts against what thirty seconds physically permits, and a hundred-catch run is the Golden Gloves standard.",
  "badges-of-ra-6-deluxe-slots": " The presentation leans fully into the fantasy: a golden marquee, five chunky reel windows with real badge artwork, and a win line that celebrates each hit payline with color and tabular coin amounts. Bets are adjustable from 10 to 2,000 BadgesCoins and every spin is resolved server-side before the reels animate, so outcomes are tamper-proof and the win cap is enforced uniformly. The scatter symbol pays independently of paylines, meaning even a losing grid can suddenly burst into profit when three Books land scattered across the reels. Regular players develop genuine preferences between the high-value symbols and the filler, and the live feed's slots entries read like a casino wall of fame: jackpots, near-misses, and the occasional big detonation that everyone in the stream witnesses together.",
  "wheel-of-fortune-and-turbo-jackpot": " The wheel's visual design follows carnival logic: a conic-gradient disc with eight segments, the Turbo segment in unmistakable gold, a pointer triangle at the top, and a deceleration curve that makes every spin feel seconds longer than it is. The result panel celebrates accordingly, with Turbo wins getting their own bordered card, bonus blog post and achievement. The once-per-day guard is strict with no exceptions and no make-ups, which is exactly what makes the daily ritual matter: miss a day and the spin is simply gone. The odds are printed on the page itself, because a jackpot whose probability is printed next to it is a promise rather than a tease. Between the printed odds, the public feed, and the automatic jackpot blog post, this is the most transparent lottery ever attached to a badge database.",
  "live-activity-feed": " The feed's engineering is intentionally simple enough to be reliable: one database table, newest-first cursor pagination, five-second client polling, and a pause control for reading. There is no websocket infrastructure to fail and no reconnection logic to debug; the feed either shows the latest truth or shows it five seconds late. Events are immutable once written, so the stream doubles as a public audit log where the sum of XP-bearing entries approximates every player's lifetime earnings. Category dots use a stable color key, so a scrolling feed can be read at a glance. For new collectors, the feed is also the best tutorial on the site: watch ten minutes of it and you will understand the economy, the games, the achievement cadence and the community's rhythm better than any documentation could teach.",
  "profile-visitors-view-counts": " The visitor system's privacy posture is worth stating plainly because view counters can go wrong in creepy ways. We store three things per visit: the profile visited, a salted hash of the visitor IP that is irreversible, and optionally the visitor's user ID when they are logged in. That is all. No raw IPs, no user agents, no referring pages. The latest-visitors widget shows only logged-in collectors, anonymous traffic moves the counter but leaves no name. Profile owners cannot export visitor data, and the five-minute dedup means even a visitor's own refreshes leave no trace trail. Meanwhile the gamified layer turns the humble hit counter into a social loop that rewards curiosity and popularity in equal measure.",
  "faq-and-blog-upgrade": " The FAQ covers twenty questions and the blog upgrade adds a third layer of documentation culture: automatic feature posts. Every system described here received its own three-hundred-word deep dive in this series, written at launch and preserved as permanent reference material. New features will join the series automatically as they ship, which means the blog grows in lockstep with the site rather than lagging behind it. View counters and emoji reactions close the loop: you can see exactly how many collectors read about the game you are playing, and a fire reaction on a strategy post is the community's way of saying the guide worked. Documentation that lives, breathes and gets counted is fitting for a site whose whole premise is counting things carefully."
};

async function main() {
  const { createFeaturePost } = await import("../src/lib/blog");
  let short = 0;
  for (const post of posts) {
    const extension = EXTENSIONS[post.slug];
    if (extension) post.content += extension;
    const words = w(post.content);
    if (words < 300) {
      console.warn(`WARN ${post.slug}: ${words} words (<300)`);
      short += 1;
    }
    await createFeaturePost({ ...post, cover: null });
    console.log(`seeded ${post.slug} (${words} words)`);
  }
  console.log(`Done: ${posts.length} posts, ${short} under 300 words.`);
  process.exit(short > 0 ? 1 : 0);
}

main().catch((error) => {
  console.error("seed failed:", error);
  process.exit(1);
});
